### ISSUE TITLE
oro:install migrations fail 'Connection refused'

### ISSUE THREAD

**Issue by Chrisissorry** [orocrm/crm#256]
Hi there,

I am trying to install OroCRM 2.0.3 into a docker container. My setup looks like this: 

```version: '2'
services:
  php:
      image: registry.example.com/devops/php
      volumes:
        - './src:/code'
      links:
          - mysql
      depends_on:
          - mysql
  nginx:
      image: nginx:1.10
      ports:
          - "80:80"
      volumes:
        - './src:/code'
        - './config/nginx:/etc/nginx'
      depends_on:
          - php
      links:
          - php
  mysql:
      image: mysql
      ports:
          - "3306:3306"
      environment:
          - MYSQL_ROOT_PASSWORD=rootpass
          - MYSQL_DATABASE=orocrm
          - MYSQL_USER=orouser
          - MYSQL_PASSWORD=pass
```

This is my `parameters.yml`:

```# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_mysql
    database_host: mysql
    database_port: 3306
    database_name: orocrm
    database_user: orouser
    database_password: pass
````

Now, when I run `php app/console oro:install --env:dev -vvv` all checks pass, the migration fails though:

```Setting up database.
Process migrations...


  [Doctrine\DBAL\Exception\ConnectionException]
  An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused



  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[HY000] [2002] Connection refused



  [PDOException]
  SQLSTATE[HY000] [2002] Connection refused


oro:migration:load [--force] [--dry-run] [--show-queries] [--bundles [BUNDLES]] [--exclude [EXCLUDE]] [--timeout [TIMEOUT]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--disabled-listeners DISABLED-LISTENERS] [--] <command>



  [RuntimeException]
  The command '/usr/local/bin/php' 'app/console' 'oro:migration:load' '--force' '--timeout=300' '--no-debug' terminated with an exit code: 1.


Exception trace:
 () at /code/vendor/oro/platform/src/Oro/Bundle/InstallerBundle/CommandExecutor.php:211
 Oro\Bundle\InstallerBundle\CommandExecutor->processResult() at /code/vendor/oro/platform/src/Oro/Bundle/InstallerBundle/CommandExecutor.php:154
 Oro\Bundle\InstallerBundle\CommandExecutor->runCommand() at /code/vendor/oro/platform/src/Oro/Bundle/InstallerBundle/Command/InstallCommand.php:454
 Oro\Bundle\InstallerBundle\Command\InstallCommand->loadDataStep() at /code/vendor/oro/platform/src/Oro/Bundle/InstallerBundle/Command/InstallCommand.php:139
 Oro\Bundle\InstallerBundle\Command\InstallCommand->execute() at /code/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /code/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:866
 Symfony\Component\Console\Application->doRunCommand() at /code/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:193
 Symfony\Component\Console\Application->doRun() at /code/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:92
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /code/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:124
 Symfony\Component\Console\Application->run() at /code/app/console:22
```

Obviously, DBAL can't connect to the database. I verified that my mysql container is reachable several times. Here's what I did:

* Wrote plain script using vanilla PDO to connect. Worked.
* Used DBAL in the plain script. Worked.
* Ran `php app/console oro:migration:load --force`. Worked! 

So when I run the migrations manually, everything works fine. Only if I use the installer, it fails. 

I cannot finish the installation. Even if the tables are present, Oro won't continue with the next step, as it tries to force table creation.

Some additional information:

* Using official php docker image with PHP 7.1.2 and all needed extensions installed
* Opcache disabled (dev environment)
* date.timezone is set
* memory_limit = -1
* max_execution_time = 0
* no install.log available

**Comment by Chrisissorry** [comment]
Alright, I ran into a timeout when installing. Running the install command with `timeout=10000` did the trick.

**Comment by mkudelya** [comment]
Thank you for your question!

**Comment by devon2018** [comment]
The same issue above is happening for me in an orocommerce application with docker.

I'm able to migrate fine using ` php app/console oro:migration:load --force` but when using the oro:install command it fails with the following error:

<img width="1175" alt="Screenshot 2021-12-07 at 14 52 37" src="https://user-images.githubusercontent.com/46196252/145051657-e187cbaa-93c7-4b43-8854-2528dfeb9211.png">

@Chrisissorry I know you had this issue quite a while ago but, i've tried adding the timeout to the install command doesn't seem to help, was there anything else you tried that might have fixed the issue.

**Comment by anyt** [comment]
If you are using the docker-compose that comes with the application together with the Symfony server and PHP runs on the host, instead of `php bin/console` you should run `symfony console` for all the commands. Otherwise, check database credentials in the config/paramters.yml file.

**Comment by devon2018** [comment]
Hi @anyt 

I'm trying to get the app working in docker without using symfony as it doesn't make sense to have both. My current docker compose looks like this.

```
version: '3'
services:
  php:
    container_name: php
    build:
      context: .
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - klere
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    links:
      - mysql
    networks:
      - klere
  mysql:
    image: mariadb:10.5.8
    ports:
      - '6767:3306'
    # labels:
    #   com.symfony.server.service-prefix: ORO_DB
    volumes:
      - mysql:/var/lib/mysql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: oro_db_pass
      MYSQL_DATABASE: oro_db
      MYSQL_USER: oro_db_user
      MYSQL_PASSWORD: oro_db_pass
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    healthcheck:
      test: "mysqladmin ping --silent -u$${MYSQL_USER} -p$${MYSQL_PASSWORD}"
    networks:
      - klere
  mailcatcher:
    image: schickling/mailcatcher
    ports: [ '1025', '1080' ]
    labels:
      com.symfony.server.service-prefix: ORO_MAILER
    networks:
      - klere
volumes:
  mysql: {}
networks:
  klere:
    driver: bridge

```

And my app dockerfile looks like this

```
FROM php:7.4-fpm

COPY docker/php.ini /usr/local/etc/php/php.ini

RUN rm /etc/apt/preferences.d/no-debian-php

RUN apt update \
    && apt install -y zlib1g-dev g++ git libicu-dev zip libzip-dev zip libxml2-dev libpng-dev \
    && docker-php-ext-install intl opcache pdo pdo_mysql soap gd \
    && pecl install apcu \
    && docker-php-ext-enable apcu \
    && docker-php-ext-configure zip \
    && docker-php-ext-configure pcntl --enable-pcntl \
    && docker-php-ext-install zip pcntl

RUN apt-get update && apt-get install -y \
    software-properties-common \
    npm
RUN npm install npm@latest -g && \
    npm install n -g && \
    n latest

WORKDIR /var/www

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Add user for laravel application
RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www

# Copy existing application directory contents
COPY . /var/www

# Copy existing application directory permissions
COPY --chown=www:www . /var/www

# Change current user to www
USER www

# Expose port 9000 and start php-fpm server
EXPOSE 9000
CMD ["php-fpm"]

```
