### ISSUE TITLE
OROCRM background tasks not running

### ISSUE THREAD

**Issue by kusgpt26** [orocrm/crm#264]
I have an installation of OROCRM working on an Amazon Lightsail VPS. Everything works except the background tasks like imports, email sync, etc.

I have installed supervisor with the following scripts
```
[program:orocrm_web_socket]
command=php /var/www/html/crm/app/console clank:server --env=prod
numprocs=1
autostart=true
startsecs=0
user=www-data
redirect_stderr=true
stderr_logfile=/var/log/oroscript.err.log
stdout_logfile=/var/log/oroscript.out.log

[program:orocrm_message_consumer]
command=php /var/www/html/crm/app/console oro:message-queue:consume --env=prod
process_name=%(program_name)s_%(process_num)02d
numprocs=5
autostart=true
autorestart=true
startsecs=0
user=www-data
redirect_stderr=true
stderr_logfile=/var/log/oroscript.err.log
stdout_logfile=/var/log/oroscript.out.log
```

I was being forced to use Supervisor with sudo and I have solved that with the chown in supervisord.conf
```
[unix_http_server]
file=/var/run/supervisor.sock   ; (the path to the socket file)
chmod=0700                       ; sockef file mode (default 0700)
chown=ubuntu:ubuntu
```

Now I see that the commands are also working
```
ubuntu@ip-XXX-XXX-XX-XX:/var/www/html/crm$ supervisorctl
orocrm_message_consumer:orocrm_message_consumer_00   RUNNING   pid 32426, uptime 0:00:05
orocrm_message_consumer:orocrm_message_consumer_01   RUNNING   pid 32430, uptime 0:00:05
orocrm_message_consumer:orocrm_message_consumer_02   RUNNING   pid 32442, uptime 0:00:03
orocrm_message_consumer:orocrm_message_consumer_03   RUNNING   pid 32434, uptime 0:00:04
orocrm_message_consumer:orocrm_message_consumer_04   RUNNING   pid 32441, uptime 0:00:04
orocrm_web_socket                                    RUNNING   pid 23408, uptime 1 day, 7:59:41
supervisor>
```

My Websocket configuation is as follows:
```
parameters:
    websocket_bind_address: 127.0.0.1
    websocket_bind_port: 8080
    websocket_frontend_host: 127.0.0.1
    websocket_frontend_port: 8080
    websocket_backend_host: 127.0.0.1
    websocket_backend_port: 8080
    web_backend_prefix: ''
```

But on the oroinstallation.com/contact page I see the following error on the top:
**_Synchronizer can't connect to server. Please contact your Administrator._**

and the console shows:
**oro.min.js?version=d64922dd:1482 WebSocket connection to 'ws://127.0.0.1:8080/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED**

When I try to validate a contacts import csv I get the message that I will receive an email on complete. I dont.
When I try to import a contacts import csv I get the message that I will receive an email on complete. I dont.

In the System > Jobs I see the following:
```
oro:import:http:oro_contact.add_or_replace:oro.58e012490.82911716             Cancelled     100%
oro:import:http:oro_contact.add_or_replace:oro.58e7ef109.20870136             Cancelled     100%
oro:import_validation:http:oro_contact.add_or_replace:oro.58e6b6dd1.33521527  Success       100%
oro.importexport.export_oro_contact	                                      Success       100%
oro:cron:run_command:oro:cron:imap-sync                                       Success       100%
oro:cron:run_command:oro:cron:send-email-campaigns                            Success       100%
```

When I do an import it shows up in the Jobs as RUNNING and stuck at 33% unless I click interupt and then it becomes CANCELLED at 100%

I've tried being very detailed about the problem, please let me know if there's any other information you need to help me debug this.

Thanks!

**Comment by sadortun** [comment]
Have you tried to run the job manually to inspect for Errors? 
Any errors in your dev/prod Logs?

**Comment by manowark** [comment]
Hi, @kusgpt26.
It seems you have incorrect configuration for websockets.
In you case I think it should be:
```
parameters:
    websocket_bind_address: 0.0.0.0 #to allow connections from other hosts
    websocket_bind_port: 8080
    websocket_frontend_host: x.x.x.x # should be address of your VPS instance
    websocket_frontend_port: 8080
    websocket_backend_host: x.x.x.x # should be address of your VPS instance
    websocket_backend_port: 8080
```

About importing. 
Please, give me version of application that you use and CSV file that you try to import. I will recheck it on my instance.
You should configure email parameters in `parameters.yml`. Also, you should set valid email into profile of your user. If email parameters and email is correct, you should receive email with link to log file with list of errors.

Please, let me know if you have more questions.

**Comment by kusgpt26** [comment]
Hi, @manowark 

Thanks for your reply.

I am using orocrm 2.0.0 version. 

I have made the exact changes you have recommended. 
```
parameters:
    websocket_bind_address: 0.0.0.0
    websocket_bind_port: 8080
    websocket_frontend_host: '*'
    websocket_frontend_port: 8080
    websocket_backend_host: '*'
    websocket_backend_port: 8080  

```
But now i get a new error :

**WebSocket connection to ‘ws://oroinstallation.com:8080/’ failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT**
